//! Cold-storage archiving for persistent outbox events.
//!
//! Old persistent events are swept out of postgres one settled span at a
//! time: the events of the span are written to object storage as JSONL
//! files (see [`EventArchiveStorage`]), recorded in the
//! `persistent_outbox_archive_chunks` manifest table, and deleted from the
//! live events table — atomically per file. Reads are unaffected from the
//! consumer's point of view: a listener resuming from a cursor below the
//! archive watermark is transparently served from object storage first,
//! then crosses over to postgres mid-stream.
//!
//! Which spans are eligible for archiving is decided by an
//! [`ArchiveBoundaryProvider`]: anything that can certify contiguous
//! history as final, at a stream position. The default
//! [`DailyRetentionBoundary`] certifies history purely by age;
//! deployments with an end-of-day process can instead certify from their
//! own marker event on the stream (e.g. an `EndOfDaySettled` whose
//! sequence closes the span), keeping late settlement-processing events
//! inside the span they belong to.
//!
//! Object storage itself is not implemented here — consumers plug in their
//! backend (GCS, S3, ...) by implementing [`EventArchiveStorage`]. An
//! [`InMemoryArchiveStorage`] is provided for tests.
//!
//! # Operator notes
//!
//! **Corrupt chunk file.** A mid-file line that does not parse aborts the
//! backfill that hit it and retries every few seconds — symptom:
//! `obix.persistent_cache.archive_backfill_failed` spans carrying a Codec
//! error, and consumers below the watermark making no progress. The chunk
//! path (in the error and in the manifest) is the format of record:
//! repair or replace the object at that path (it can be regenerated by
//! re-exporting the span — deleting the manifest row lets the archiver
//! sweep it again). A torn *final* line (truncated write) does not wedge:
//! it degrades to placeholder deliveries for the chunk's tail, traced via
//! `obix.archive.line_torn`.
//!
//! **Missing archive reader.** Every pod that might serve pre-watermark
//! reads must be configured with the same [`ArchiveConfig`]. A pod
//! without it degrades to placeholder deliveries below the watermark
//! (`obix.persistent_cache.archive_reader_missing`, warn) — loud but
//! degraded.

mod archiver;
mod boundary;
mod codec;
mod error;
mod job;
mod reader;
mod storage;

use es_entity::clock::{Clock, ClockHandle};

use std::sync::Arc;

use crate::{out::OutboxEventId, sequence::EventSequence};

pub use archiver::{ArchiveRunReport, EventArchiver};
pub use boundary::{ArchiveBoundaryProvider, DailyRetentionBoundary};
pub use error::ArchiveError;
pub use job::OutboxArchiverJobConfig;
pub use storage::{EventArchiveStorage, InMemoryArchiveStorage};

pub(crate) use job::{OutboxArchiverJobData, OutboxArchiverJobInitializer};
pub(crate) use reader::ArchiveReader;

/// Roll the current file over once it exceeds this size. Approximate — the
/// rollover happens between events, never mid-event.
pub const DEFAULT_TARGET_FILE_BYTES: usize = 16 * 1024 * 1024;

/// Compression applied to chunk files at write time.
///
/// The format is encoded in each chunk's file extension (`.jsonl` vs
/// `.jsonl.gz`), so readers sniff the path rather than the config: a
/// deployment can flip this setting at any time — or roll back — and old
/// chunks stay readable. Default [`Compression::None`]: upgrading obix
/// never changes the format of new writes unless opted in.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Compression {
    /// Plain JSONL.
    #[default]
    None,
    /// gzip-compressed JSONL (pure-Rust miniz_oxide backend).
    Gzip,
}

impl Compression {
    pub(crate) fn encode(self, data: &[u8]) -> Result<bytes::Bytes, ArchiveError> {
        match self {
            Self::None => Ok(bytes::Bytes::copy_from_slice(data)),
            Self::Gzip => codec::gzip_encode(data),
        }
    }

    /// Decode fetched object bytes according to the chunk path's
    /// extension — the path is the format of record, see above.
    pub(crate) fn decode_path(
        path: &str,
        data: bytes::Bytes,
    ) -> Result<bytes::Bytes, ArchiveError> {
        if path.ends_with(".gz") {
            codec::gzip_decode(data)
        } else {
            Ok(data)
        }
    }

    pub(crate) fn file_extension(self) -> &'static str {
        match self {
            Self::None => "jsonl",
            Self::Gzip => "jsonl.gz",
        }
    }
}

const DEFAULT_EXPORT_PAGE_SIZE: usize = 1000;

/// A contiguous, settled boundary: all events up to and including
/// `up_to_sequence` are certified final and eligible for archiving.
/// Boundaries are consumed oldest-first; each becomes one labeled group
/// of JSONL files in the archive.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchiveBoundary {
    /// Deployment-chosen label for the span this boundary closes, used as
    /// the path segment grouping its files (e.g. a calendar date like
    /// `"2026-07-20"`). obix attaches no meaning to it beyond naming.
    pub label: String,
    /// Inclusive end of the settled history.
    pub up_to_sequence: EventSequence,
}

/// One exported JSONL file, as recorded in the
/// `persistent_outbox_archive_chunks` manifest table. Chunks are contiguous:
/// the next chunk starts at `max_sequence + 1` of the previous one.
///
/// Any grouping label (e.g. a calendar date) is encoded in the chunk's
/// `path` — the manifest itself is purely sequence bookkeeping.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchiveChunk {
    /// Object-storage path the file was written to.
    pub path: String,
    pub min_sequence: EventSequence,
    pub max_sequence: EventSequence,
}

/// A raw persistent event row as exported to the archive: the payload is
/// still the stored JSON — the archiver is payload-type-agnostic. Decoding
/// into a concrete event type happens on read, through the same path as
/// live events.
#[derive(Debug)]
pub struct RawExportRow {
    pub id: OutboxEventId,
    pub sequence: EventSequence,
    /// `None` is a sequence placeholder, exactly as in the live table.
    pub payload: Option<serde_json::Value>,
    pub tracing_context: Option<serde_json::Value>,
    pub recorded_at: chrono::DateTime<chrono::Utc>,
}

/// Archiving configuration for an [`Outbox`](crate::Outbox).
///
/// Set on [`MailboxConfig::archive`](crate::MailboxConfig) — the outbox
/// then serves pre-watermark reads from the archive, and
/// [`Outbox::register_event_archiver`](crate::Outbox::register_event_archiver)
/// can schedule the sweep job.
#[derive(Clone)]
pub struct ArchiveConfig {
    /// The object-storage backend chunks are written to / read from.
    pub storage: Arc<dyn EventArchiveStorage>,
    /// Decides which spans are eligible for archiving.
    pub boundary: Arc<dyn ArchiveBoundaryProvider>,
    /// Prepended to every chunk path, e.g. `"lana/core-outbox/"`.
    pub path_prefix: String,
    /// Cap on settled spans one archiver run sweeps — a pacing knob for
    /// very large first catch-ups. One run sweeps everything its single
    /// `pending_boundaries` listing returned, up to this cap; a catch-up
    /// reschedules until current. Default 100.
    pub boundaries_per_run: usize,
    /// Start a new file once the current one exceeds this size, see
    /// [`DEFAULT_TARGET_FILE_BYTES`]. Bounds memory on write and read —
    /// files are buffered whole.
    pub target_file_bytes: usize,
    /// Rows fetched per postgres page during export.
    pub export_page_size: usize,
    /// Compression applied to new chunk files; reads always sniff the
    /// chunk path, see [`Compression`].
    pub compression: Compression,
    pub clock: ClockHandle,
}

impl ArchiveConfig {
    pub fn new(
        storage: Arc<dyn EventArchiveStorage>,
        boundary: Arc<dyn ArchiveBoundaryProvider>,
    ) -> Self {
        Self {
            storage,
            boundary,
            path_prefix: String::new(),
            boundaries_per_run: 100,
            target_file_bytes: DEFAULT_TARGET_FILE_BYTES,
            export_page_size: DEFAULT_EXPORT_PAGE_SIZE,
            compression: Compression::None,
            clock: Clock::handle().clone(),
        }
    }

    pub fn with_path_prefix(mut self, prefix: impl Into<String>) -> Self {
        self.path_prefix = prefix.into();
        self
    }

    pub fn with_boundaries_per_run(mut self, boundaries_per_run: usize) -> Self {
        self.boundaries_per_run = boundaries_per_run.max(1);
        self
    }

    pub fn with_target_file_bytes(mut self, target_file_bytes: usize) -> Self {
        self.target_file_bytes = target_file_bytes.max(1);
        self
    }

    pub fn with_export_page_size(mut self, export_page_size: usize) -> Self {
        self.export_page_size = export_page_size.max(1);
        self
    }

    pub fn with_compression(mut self, compression: Compression) -> Self {
        self.compression = compression;
        self
    }

    pub fn with_clock(mut self, clock: ClockHandle) -> Self {
        self.clock = clock;
        self
    }

    pub(crate) fn reader(&self) -> ArchiveReader {
        ArchiveReader::new(self.storage.clone(), self.clock.clone())
    }
}
